version: "3.9"
services:
  postgresql:
    image: postgres:15-alpine
    container_name: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    networks:
      - shared
  s3:
    image: minio/minio
    container_name: s3
    command: server --console-address ":9090" /data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "9090:9090"
    networks:
      - shared
    volumes:
      - ./tmp/s3/:/data
  redis:
    image: "redis:alpine"
    container_name: redis
    command: redis-server --requirepass password
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - shared
  asynqmon:
    image: hibiken/asynqmon
    container_name: asynqmon
    environment:
      - PORT=3000
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=password
    depends_on:
      - redis
    ports:
      - "6000:3000"
    networks:
      - shared
  async:
    build:
      context: .
    image: async
    container_name: async
    command: air --build.cmd "go build -o ./tmp/async ./cmd/async/main.go" --build.bin "./tmp/async" --build.exclude_dir "frontend"
    environment:
      - ENVIRONMENT=local
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_NAME=db
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_SSL_MODE=disable
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_ENDPOINT=http://s3:9000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
    networks:
      - shared
    depends_on:
      - postgresql
      - redis
    volumes:
      - ./:/app
      - $HOME/golang/:/go
  api:
    build:
      context: .
    image: api
    container_name: api
    command: air --build.cmd "go build -o ./tmp/api ./cmd/api/main.go" --build.bin "./tmp/api" --build.exclude_dir "frontend"
    environment:
      - ENVIRONMENT=local
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_NAME=db
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_SSL_MODE=disable
      - JWT_SECRET_KEY=Zq4t7w!z%C*F-JaNcRfUjXn2r5u8x/A?
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_ENDPOINT=http://s3:9000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
    ports:
      - "8080:8080"
    networks:
      - shared
    depends_on:
      - postgresql
      - s3
      - redis
      - async
    volumes:
      - ./:/app
      - $HOME/golang/:/go

networks:
  shared:
    driver: bridge
    name: shared
