version: "3.9"
services:
  postgres-db:
    image: postgres:15-alpine
    container_name: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
  web:
    build:
      context: .
    image: web
    container_name: thesis-pieces
    environment:
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_NAME=db
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_SSL_MODE=disable
      - JWT_SECRET_KEY=Zq4t7w!z%C*F-JaNcRfUjXn2r5u8x/A?
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    volumes:
      - ./:/app
      - $HOME/golang/:/go
