// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package store

import (
	"time"

	"github.com/google/uuid"
)

type Document struct {
	ID          int32
	Uuid        uuid.UUID
	UserID      int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Description string
	Filename    string
	Filetype    string
	Content     *string
	Ts          interface{}
}

type User struct {
	ID        int32
	Uuid      uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Username  string
	Email     string
	Password  string
	FirstName string
	LastName  string
	IsAdmin   bool
}
